### PR TITLE
Proposition for issues #1, #3

### PR DESCRIPTION
**Pull request by hucste**
Modify codes to issues #1, #3.

### CODE REVIEW

**Comment by plegall** [comment]
Hi @hucste 

How do you manage update from previous version of the plugin? Which "business" (email address) will be used?

**Comment by hucste** [comment]
Interesting idea... for the moment, i dont! sorry...
because, you can fill business into admin by the mail :p 

But i can modify code to manage this, in admin... as: 
if empty(business) business=mail 

good for you?

**Comment by plegall** [comment]
Yes, it would be fine. The idea is to let users update to the new version without their Shopping cart to be broken :-)

**Comment by hucste** [comment]
Ok, close this... and, during i modify the code! ;)

**Pull request closed without merging**
